[package]
	name = "stelofinance"
	version = "0.5.0"
	edition = "2024"

[dependencies]
	openidconnect = "4.0.1"
	tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
	topcoat = { version = "0.5.0", features = ["tailwind"] }

[build-dependencies]
	topcoat = { version = "0.5.0", default-features = false, features = [
		"tailwind",
	] }
