# fly.toml app configuration file generated for stelofinance on 2024-12-08
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "stelofinance"
primary_region = "iad"

[env]
	PORT = "8080"
	ENV = "prod"
	JS_DIR = "/data/nats"
	DB_FILE = "/data/prod.db"
	GOOSE_DRIVER = "sqlite3"
	GOOSE_DBSTRING = "/data/prod.db"

[mounts]
	source = "data"
	destination = "/data"
	initial_size = "1gb"
	auto_extend_size_threshold = 90
	auto_extend_size_limit = "50gb"
	auto_extend_size_increment = "1gb"

[http_service]
	internal_port = 8080
	force_https = true
	auto_stop_machines = "suspend"
	auto_start_machines = true
	min_machines_running = 1
	# processes = ["app"]

	[[http_service.checks]]
		grace_period = "10s"
		interval = "30s"
		method = "GET"
		timeout = "5s"
		path = "/api/ping"


[[vm]]
	size = "shared-cpu-1x"
	memory = "256mb"
