version: '3'

interval: 50ms

env:
  STATIC_DIR: "web/static"

tasks:
  live:
    desc: Run live dev environment
    cmds:
      - task live:styles &
      - task live:go

  live:styles:
    cmds:
      - "tailwindcss -i web/styles/tw-input.css -o {{.STATIC_DIR}}/tw-output.css --minify --watch"

  live:go:
    deps: [live:go:run]
    watch: true
    # Copies build:go so that it gets rerun
    sources:
      - "**/*.go"

  live:go:run:
    deps: [build:go]
    cmds:
      - bin/app

  build:
    desc: Build all artifacts
    deps: [build:go, build:styles]

  build:go:
    env:
      GOARCH: amd64
      GOOS: linux
      CGO_ENABLED: 0
    cmds: 
      - go build -o bin/app cmd/app/main.go
    sources:
      - "**/*.go"
    generates:
      - bin/app

  build:styles:
    cmds:
      - "tailwindcss -i web/styles/tw-input.css -o {{.STATIC_DIR}}/tw-output.css --minify"
    sources:
      - "web/**/*.{html,go}"
      - tailwind.config.js
    generates:
      - web/static/tw-output.css

  run:
    desc: Run Stelo Finance
    cmds:
      - bin/app
    deps: [build]
