-- +goose Up
CREATE TABLE IF NOT EXISTS "user"
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    discord_id TEXT NOT NULL UNIQUE,
    discord_username TEXT NOT NULL,
    discord_pfp TEXT,
    bitcraft_username TEXT,
    created_at TIMESTAMPTZ NOT NULL
);
-- +goose Down
DROP TABLE IF EXISTS "user";
