-- +goose Up
CREATE TABLE IF NOT EXISTS wallet
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    address TEXT NOT NULL UNIQUE,
    code INT NOT NULL,
    webhook TEXT,
    location GEOMETRY(POINT),

    created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS wallet_permission
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    wallet_id BIGINT NOT NULL REFERENCES wallet(id),
    user_id BIGINT NOT NULL REFERENCES "user"(id),
    permissions BIGINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS ledger
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE,
    asset_scale INT NOT NULL,
    code INT NOT NULL,
    value INT NOT NULL
);
CREATE TABLE IF NOT EXISTS account
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    wallet_id BIGINT NOT NULL REFERENCES wallet(id),
    debits_pending BIGINT NOT NULL,
    debits_posted BIGINT NOT NULL,
    credits_pending BIGINT NOT NULL,
    credits_posted BIGINT NOT NULL,
    ledger_id BIGINT NOT NULL REFERENCES ledger(id),
    code INT NOT NULL,
    flags BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS transaction
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    debit_wallet_id BIGINT NOT NULL REFERENCES wallet(id),
    credit_wallet_id BIGINT NOT NULL REFERENCES wallet(id),
    code INT NOT NULL,
    memo TEXT,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS transfer
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    transaction_id BIGINT NOT NULL REFERENCES transaction(id),
    debit_account_id BIGINT NOT NULL REFERENCES account(id),
    credit_account_id BIGINT NOT NULL REFERENCES account(id),
    amount BIGINT NOT NULL,
    pending_id BIGINT REFERENCES transfer(id),
    ledger_id BIGINT NOT NULL REFERENCES ledger(id),
    code INT NOT NULL,
    flags BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

-- Add rest of fields to account
ALTER TABLE wallet
    ADD COLUMN collateral_account_id BIGINT REFERENCES account(id),
    ADD COLUMN collateral_locked_account_id BIGINT REFERENCES account(id),
    ADD COLUMN collateral_percentage DECIMAL(4, 3);

-- +goose Down
ALTER TABLE wallet
    DROP COLUMN collateral_account_id,
    DROP COLUMN collateral_locked_account_id,
    DROP COLUMN collateral_percentage;

DROP TABLE IF EXISTS transfer;
DROP TABLE IF EXISTS transaction;
DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS ledger;
DROP TABLE IF EXISTS wallet_permission;
DROP TABLE IF EXISTS wallet;
