mod app;
mod auth;
mod einro;
// Generated by `spacetime generate` / `task stdb:generate` — do not edit by hand.
mod module_bindings;
mod stdb;
mod ui;

#[tokio::main]
async fn main() {
	topcoat::start(app::router().await).await.unwrap();
}
